export enum TransactionsStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  PAYMENT_REQUEST_PENDING = 'PAYMENT_REQUEST_PENDING',
  PAYMENT_REQUEST_SUCCESS = 'PAYMENT_REQUEST_SUCCESS',
  PAYMENT_REQUEST_FAILED = 'PAYMENT_REQUEST_FAILED',
}
